### ISSUE TITLE
RuntimeWarning

### ISSUE THREAD

**Issue by alexmay21** [VincentLiu3/Tensor-Factorization#1]
when i train the model,there are some issues as followings:
TF.py:88: RuntimeWarning: overflow encountered in mulyiply
    step_S += lrS * e_ijk * reduce(np.multiply.outer, Ui_list)
TF.py:88: RuntimeWarning: invalid value encountered in add
    step_S += lrS * e_ijk * reduce(np.multiply.outer, Ui_list)

**Comment by VincentLiu3** [comment]
You can try to decrease the learning rates (lr and lrS) until there is no overflow issue.

**Comment by alexmay21** [comment]
Thank you for your generous help!
